config/routes.rb
Bowlingdb::Application.routes.draw do
  namespace "admin" do
    resources :categories, :locations, :players
    resources :stats, :only => [:index, :show]
    resources :match_days do
      resources :games
    end
  end

  resources :match_days, :only => [:index, :show] do
    collection do
      get 'latest'
    end
  end

  resources :player, :only => [:show]

  match ':controller(/:action)'

  root :to => 'match_days#latest'

end

app/models/location.rb
class Location < ActiveRecord::Base
   attr_accessible :name
   validates :name, :presence => true

   has_many :match_day, :inverse_of => :location, :dependent => :destroy

   def self.locations_for_selection
     Location.all(:order => 'name').map { |l|
       [l.name, l.id]
     }
   end
end

app/controllers/admin/locations_controller.rb
class Admin::LocationsController < Admin::BaseController
  def index
    @locations = Location.order("name")
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(params[:location])
    if @location.save
      redirect_to :action => :index
    else
      render :action => :new
    end
  end

  def edit
    @location = Location.find(params[:id])
  end

  def update
    @location = Location.find(params[:id])
    if @location.update_attributes(params[:location])
      redirect_to :action => :index
    else
      render :action => :edit
    end
  end

  def destroy
    @location = Location.find(params[:id])
    @location.destroy
    redirect_to :action => :index
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/admin/locations/_form.html.erb
<%= form_for [:admin, @location], :html => { :class => "form-horizontal" } do |f| %>
  <% if @location.errors.any? %>
    <div id="errorExplanation">
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </div>
  <% end %>

  <div class="control-group">
    <label class="control-label">Name</label>
    <div class="controls"><%= f.text_field :name %></div>
  </div>
  <div class="control-group">
    <label class="control-label"></label>
    <div class="controls">
      <%= f.submit 'Speichern', :class => "btn btn-primary" %>
      <%= link_to 'Abbrechen', admin_locations_path, :class => "btn" %>
    </div>
  </div>
<% end %>				    

app/views/admin/locations/edit.html.erb
<%= render 'form' %>

app/views/admin/locations/index.html.erb
<p><%= link_to "Neuer Spielort", { :action => :new }, { :class => "btn btn-primary" } %></p>
<table class="table">
  <% @locations.each do |location| %>
    <tr>
      <td><%= location.name %></td>
      <td>
        <div class="btn-group">
	  <%= link_to 'Bearbeiten', edit_admin_location_path(location), :class => "btn btn-primary" %>
          <%= link_to 'Löschen', [:admin, location], :method => :delete, :class => "btn btn-danger" %>
	</div>
      </td>
    </tr>
  <% end %>
</table>
<p><%= link_to "Neuer Spielort", { :action => :new }, { :class => "btn btn-primary" } %></p>

app/views/admin/locations/new.html.erb
<%= render 'form' %>