config/routes.rb
Bowlingdb::Application.routes.draw do
  namespace "admin" do
    resources :categories, :locations, :players
    resources :stats, :only => [:index, :show]
    resources :match_days do
      resources :games
    end
  end

  resources :match_days, :only => [:index, :show] do
    collection do
      get 'latest'
    end
  end

  resources :player, :only => [:show]

  match ':controller(/:action)'

  root :to => 'match_days#latest'

end

app/controllers/highscores_controller.rb
require 'will_paginate/array'

class HighscoresController < ReportController
  WillPaginate.per_page = 20

  def by_player
    @games = []
    Game.joins(:match_day).select('player_id, MAX(points) AS points').where(:player_id => @player_restrictions, 'match_days.location_id' => @location_restrictions, 'match_days.category_id' => @category_restrictions).where('match_days.match_day >= ? AND match_days.match_day <= ?', @date_from_restriction.match_day, @date_to_restriction.match_day).group('player_id').each do |row|
      @games << Game.joins(:match_day).where(:player_id => row.player_id, :points => row.points).order('match_days.match_day DESC').first
    end
    @games = sort(@games).paginate(:page => params[:page])
    render :results
  end

  def by_match_day
    @games = []
    Game.joins(:match_day).select('match_day_id, player_id, COUNT(*) AS game_count, SUM(points) AS points, SUM(cleared_frames) AS cleared_frames, SUM(strikes) AS strikes, SUM(spares) AS spares, SUM(splits) AS splits, SUM(cleared_splits) AS cleared_splits, SUM(fouls) AS fouls').where(:player_id => @player_restrictions, 'match_days.location_id' => @location_restrictions, 'match_days.category_id' => @category_restrictions).where('match_days.match_day >= ? AND match_days.match_day <= ?', @date_from_restriction.match_day, @date_to_restriction.match_day).group(:match_day_id, :player_id).each do |row|
      game = Game.new
      game.number = row.game_count
      game.match_day = MatchDay.find(row.match_day_id)
      game.player = Player.find(row.player_id)
      game.points = row.points
      game.cleared_frames = row.cleared_frames
      game.strikes = row.strikes
      game.spares = row.spares
      game.splits = row.splits
      game.cleared_splits = row.cleared_splits
      game.fouls = row.fouls
      @games << game
    end
    @games = sort(@games).paginate(:page => params[:page])
    render :results
  end

  def by_games
    @games = Game.joins(:match_day).where(:player_id => @player_restrictions, 'match_days.location_id' => @location_restrictions, 'match_days.category_id' => @category_restrictions).where('match_days.match_day >= ? AND match_days.match_day <= ?', @date_from_restriction.match_day, @date_to_restriction.match_day)
    @games = sort(@games).paginate(:page => params[:page])
    render :results
  end

  def by_avg_match_day
    @games = []
    Game.connection.select_all(
      'SELECT match_day_id, player_id, COUNT(*) AS game_count, AVG(points) AS points, AVG(cleared_frames) AS cleared_frames, AVG(strikes) AS strikes, AVG(spares) AS spares, AVG(splits) AS splits, AVG(cleared_splits) AS cleared_splits, AVG(fouls) AS fouls
      FROM games INNER JOIN match_days ON games.match_day_id = match_days.id
      WHERE ' + get_restrictions_as_sql + '
      GROUP BY match_day_id, player_id
      ORDER BY points DESC, strikes DESC, spares DESC, cleared_splits DESC, cleared_frames DESC, splits ASC'
    ).each do |row|
      game = UntypedGame.new
      game.number = row['game_count']
      game.match_day = MatchDay.find(row['match_day_id'])
      game.player = Player.find(row['player_id'])
      game.points = row['points']
      game.cleared_frames = row['cleared_frames']
      game.strikes = row['strikes']
      game.spares = row['spares']
      game.splits = row['splits']
      game.cleared_splits = row['cleared_splits']
      game.fouls = row['fouls']
      @games << game
    end
    @games = sort(@games).paginate(:page => params[:page])
    render :results_avg
  end
end

app/helpers/highscores_helper.rb
module HighscoresHelper
end

app/views/highscores/results.html.erb
<%= render 'shared/score_restrictions' %>

<%= will_paginate @games, :renderer => BootstrapPagination::Rails %>

<table class="table">
  <tr>
    <th>Spieler</th>
    <th class="text-center">Spiel</th>
    <th class="text-center"><%= sortable "points", "Punkte" %></th>
    <th class="text-center"><%= sortable "cleared_frames", "Geräumt" %></th>
    <th class="text-center"><%= sortable "strikes" %></th>
    <th class="text-center"><%= sortable "spares" %></th>
    <th class="text-center"><%= sortable "splits" %></th>
    <th class="text-center"><%= sortable "fouls" %></th>
    <th class="text-center">Datum</th>
    <th>Ort</th>
    <th>Kategorie</th>
  </tr>
  <% @games.each do |game| %>
    <tr>
      <td><%= link_to game.player.full_name, player_path(game.player) %></td>
      <td class="text-center"><%= game.number %></td>
      <td class="text-center"><%= game.points %></td>
      <td class="text-center"><%= game.cleared_frames %></td>
      <td class="text-center"><%= game.strikes %></td>
      <td class="text-center"><%= game.spares %></td>
      <td class="text-center"><%= game.splits %> (<%= game.cleared_splits %>)</td>
      <td class="text-center"><%= game.fouls %></td>
      <td class="text-center"><%= link_to game.match_day.formatted_match_day, match_day_path(game.match_day) %></td>
      <td><%= game.match_day.location.name %></td>
      <td><%= game.match_day.category.name %></td>
    </tr>
  <% end %>
</table>

app/views/highscores/results_avg.html.erb
<%= render 'shared/score_restrictions' %>

<%= will_paginate @games, :renderer => BootstrapPagination::Rails %>

<table class="table">
  <tr>
    <th>Spieler</th>
    <th class="text-center">Spiel</th>
    <th class="text-center"><%= sortable "points", "Punkte" %></th>
    <th class="text-center"><%= sortable "cleared_frames", "Geräumt" %></th>
    <th class="text-center"><%= sortable "strikes" %></th>
    <th class="text-center"><%= sortable "spares" %></th>
    <th class="text-center"><%= sortable "splits" %></th>
    <th class="text-center"><%= sortable "fouls" %></th>
    <th class="text-center">Datum</th>
    <th>Ort</th>
    <th>Kategorie</th>
  </tr>
  <% @games.each do |game| %>
    <tr>
      <td><%= link_to game.player.full_name, player_path(game.player) %></td>
      <td class="text-center"><%= game.number %></td>
      <td class="text-center"><%= '%.2f' % game.points.round(2) %></td>
      <td class="text-center"><%= '%.2f' % game.cleared_frames.round(2) %></td>
      <td class="text-center"><%= '%.2f' % game.strikes.round(2) %></td>
      <td class="text-center"><%= '%.2f' % game.spares.round(2) %></td>
      <td class="text-center"><%= '%.2f' % game.splits.round(2) %> (<%= '%.2f' % game.cleared_splits.round(2) %>)</td>
      <td class="text-center"><%= '%.2f' % game.fouls.round(2) %></td>
      <td class="text-center"><%= link_to game.match_day.formatted_match_day, match_day_path(game.match_day) %></td>
      <td><%= game.match_day.location.name %></td>
      <td><%= game.match_day.category.name %></td>
    </tr>
  <% end %>
</table>