config/routes.rb
Bowlingdb::Application.routes.draw do
  namespace "admin" do
    resources :categories, :locations, :players
    resources :stats, :only => [:index, :show]
    resources :match_days do
      resources :games
    end
  end

  resources :match_days, :only => [:index, :show] do
    collection do
      get 'latest'
    end
  end

  resources :player, :only => [:show]

  match ':controller(/:action)'

  root :to => 'match_days#latest'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  validates :name, :presence => true

  has_many :match_day, :inverse_of => :category, :dependent => :destroy
  
  def self.categories_for_selection
    Category.all(:order => 'name').collect { |c|
      [c.name, c.id]
    }
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  def index
    @categories = Category.order("name")
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params[:category])
    if @category.save
      redirect_to :action => :index
    else
      render :action => :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(params[:category])
      redirect_to :action => :index
    else
      render :action => :edit
    end
  end

  def destroy 
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to :action => :index
   end
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category], :html => { :class => "form-horizontal" } do |f| %>
  <% if @category.errors.any? %>
    <div id="errorExplanation">
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </div>
  <% end %>

  <div class="control-group">
    <label class="control-label">Name</label>
    <div class="controls"><%= f.text_field :name %></div>
  </div>
  <div class="control-group">
    <label class="control-label"></label>
    <div class="controls">
      <%= f.submit 'Speichern', :class => "btn btn-primary" %>
      <%= link_to 'Abbrechen', admin_categories_path, :class => "btn" %>
    </div>
  </div>
<% end %>				    

app/views/admin/categories/edit.html.erb
<%= render 'form' %>

app/views/admin/categories/index.html.erb
<p><%= link_to "Neue Kategorie", { :action => :new }, { :class => "btn btn-primary" } %></p>
<table class="table">
  <% @categories.each do |category| %>
    <tr>
      <td><%= category.name %></td>
      <td>
        <div class="btn-group">
	  <%= link_to 'Bearbeiten', edit_admin_category_path(category), :class => "btn btn-primary" %>
          <%= link_to 'Löschen', [:admin, category], :method => :delete, :class => "btn btn-danger" %>
	</div>
      </td>
    </tr>
  <% end %>
</table>
<p><%= link_to "Neue Kategorie", { :action => :new }, { :class => "btn btn-primary" } %></p>

app/views/admin/categories/new.html.erb
<%= render 'form' %>